version: '3.4'

services:
  db:
    image: mysql:8.0
    command: --init-file /docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - sameNetworkAsMysql # Connects the service to the 'sameNetworkAsMysql' network
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./data:/var/lib/mysql
  backend:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    networks:
      - sameNetworkAsMysql # Connects the service to the 'sameNetworkAsMysql' network
    depends_on: 
      - db
  frontend:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - sameNetworkAsMysql # Connects the service to the 'sameNetworkAsMysql' network
    depends_on:
      - backend
networks:
  sameNetworkAsMysql: # Defines the 'sameNetworkAsMysql' network
    driver: bridge # Specifies the network driver as 'bridge'