version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --init-file /docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./data:/var/lib/mysql

  backend:
    build:
      context: server
      dockerfile: ./Dockerfile
      target: development
    ports:
      - 3001:3001
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    
  frontend:
    build:
      context: client
      dockerfile: ./Dockerfile
      target: development
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

networks:
  app-network:
    driver: bridge